# This file contains configuration options for GolangCI-Lint
# https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - gofmt
    - goimports

run:
  timeout: 5m 