# Docker Compose for Prompt Alchemy MCP Server with Ollama
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: prompt-alchemy-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  prompt-alchemy-mcp:
    build: .
    container_name: prompt-alchemy-mcp-server
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./docker-config-ollama.yaml:/app/config.yaml
    environment:
      - PROMPT_ALCHEMY_CONFIG=/app/config.yaml
    # Run MCP server (stdio-based JSON-RPC)
    entrypoint: ["prompt-alchemy", "serve", "--config", "/app/config.yaml"]
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ollama_data: