version: '3.8'

# Development override for live testing with hot reload
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml --profile hybrid up
# This enables instant UI updates without rebuilding containers

services:
  # API Server with potential for hot reload
  prompt-alchemy:
    volumes:
      # Mount source code for potential hot reload with air or similar tool
      - ./internal:/app/internal:ro
      - ./pkg:/app/pkg:ro
      - ./cmd:/app/cmd:ro
      - ./docker-config.yaml:/app/config.yaml:ro
    environment:
      - GO_ENV=development
      - DEBUG=true
    restart: "no"

  # Web UI with live reload
  prompt-alchemy-web:
    volumes:
      # Mount web directory for instant UI changes
      - ./web:/app/web:ro
      # Specifically mount static and template directories
      - ./web/static/js:/app/web/static/js:ro
      - ./web/static/css:/app/web/static/css:ro
      - ./web/templates:/app/web/templates:ro
    environment:
      - LIVE_RELOAD=true
      - DEBUG=true
      - DEVELOPMENT=true
    # Restart policy for development
    restart: "no"
    # Add development port for hot reload if implemented
    ports:
      - "8090:8090"
      - "35729:35729" # LiveReload port
    
  # Development test runner service
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - ./tests:/app/tests:ro
      - ./web:/app/web:ro
      - ./test-results:/app/test-results
    depends_on:
      - prompt-alchemy-web
    environment:
      - BASE_URL=http://prompt-alchemy-web:8090
    profiles:
      - dev-test