version: '3.8'

services:
  prompt-alchemy-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5747:8080"
      - "5748:8080"
    environment:
      - DATA_DIR=/data
      - LOG_LEVEL=debug
      - PROMPT_ALCHEMY_PROVIDERS_OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - PROMPT_ALCHEMY_PROVIDERS_ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - PROMPT_ALCHEMY_PROVIDERS_GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - PROMPT_ALCHEMY_GENERATION_DEFAULT_PROVIDER=openai
    volumes:
      - ./data:/data
      - ./configs:/app/configs:ro
    restart: unless-stopped
    command: ["./prompt-alchemy", "serve", "--api", "--mcp", "--host", "0.0.0.0", "--port", "8080"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend development server (optional, for integrated development)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      - VITE_API_URL=http://localhost:8080
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - prompt-alchemy-api
    profiles:
      - frontend

volumes:
  data: