# Docker Compose for Prompt Alchemy with API Keys
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: prompt-alchemy-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  prompt-alchemy:
    build: .
    container_name: prompt-alchemy-server-with-keys
    ports:
      - "9090:8080"
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./docker-config-with-keys.yaml:/app/config.yaml
    env_file:
      - .env
    environment:
      - PROMPT_ALCHEMY_CONFIG=/app/config.yaml
      # Map .env variables to the format expected by the app
      - PROMPT_ALCHEMY_PROVIDERS_OPENAI_API_KEY=${OPENAI_API_KEY}
      - PROMPT_ALCHEMY_PROVIDERS_OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PROMPT_ALCHEMY_PROVIDERS_ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PROMPT_ALCHEMY_PROVIDERS_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  ollama_data: