version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-vector-db
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qdrant-network

  # Qdrant with persistence and backup
  qdrant-backup:
    image: qdrant/qdrant:latest
    container_name: qdrant-backup
    profiles:
      - backup
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./backups:/backups
    command: |
      bash -c "
        mkdir -p /backups &&
        cp -r /qdrant/storage/* /backups/ &&
        echo 'Backup completed at $(date)'
      "

volumes:
  qdrant_storage:
    driver: local

networks:
  qdrant-network:
    driver: bridge