providers:
  # Ollama for local testing (doesn't require API keys)
  ollama:
    enabled: true
    base_url: "http://host.docker.internal:11434"
    model: "llama2"
    timeout: 30

# Use ollama as default since it doesn't require API keys
phases:
  prima-materia:
    provider: "ollama"
  solutio:
    provider: "ollama"
  coagulatio:
    provider: "ollama"

# Data storage (container path)
data_dir: "/app/data"

# Logging
log_level: "info"

# HTTP server config
http:
  host: "0.0.0.0"
  port: 8080
  cors:
    enabled: true
    origins: ["*"]
  auth:
    enabled: false

# Learning disabled for demo
learning:
  enabled: false

# Ranking configuration
ranking:
  weights:
    temperature: 0.2
    token: 0.2
    semantic: 0.3
    length: 0.1
    historical: 0.2