# GitHub Pages Configuration - Improved Version
theme: jekyll-theme-minimal
title: Prompt Alchemy
description: Transform raw ideas into golden prompts through the ancient art of linguistic alchemy
logo: /prompt-alchemy/assets/prompt_alchemy2.png
baseurl: "/prompt-alchemy"
url: "https://jonwraymond.github.io"

# SEO Enhancements
author: Jon Raymond
twitter:
  username: jonwraymond
  card: summary_large_image
social:
  name: Prompt Alchemy
  links:
    - https://github.com/jonwraymond/prompt-alchemy

# Branding
brand:
  primary_color: "#C9A96E"
  secondary_color: "#8B4513"
  accent_color: "#DAA520"
  text_color: "#2C1810"
  background_color: "#FFF8DC"

# Improved Navigation - Grouped Structure
navigation:
  - title: "🚀 Getting Started"
    children:
      - title: Home
        url: /prompt-alchemy/
      - title: Getting Started
        url: /prompt-alchemy/getting-started
      - title: Installation
        url: /prompt-alchemy/installation
      - title: Usage Guide
        url: /prompt-alchemy/usage
      - title: Quick Reference
        url: /prompt-alchemy/mode-quick-reference
  
  - title: "📖 API Reference"
    children:
      - title: CLI Reference
        url: /prompt-alchemy/cli-reference
      - title: HTTP API Reference
        url: /prompt-alchemy/http-api-reference
      - title: MCP API Reference
        url: /prompt-alchemy/mcp-api-reference
      - title: MCP Integration
        url: /prompt-alchemy/mcp-integration
      - title: Client Interaction Modes
        url: /prompt-alchemy/client-interaction-modes
  
  - title: "🏗️ Architecture"
    children:
      - title: Architecture Overview
        url: /prompt-alchemy/architecture
      - title: Database Schema
        url: /prompt-alchemy/database
      - title: Vector Embeddings
        url: /prompt-alchemy/vector-embeddings
      - title: Diagrams
        url: /prompt-alchemy/diagrams
  
  - title: "🚀 Deployment"
    children:
      - title: Deployment Guide
        url: /prompt-alchemy/deployment-guide
      - title: On-Demand vs Server Mode
        url: /prompt-alchemy/on-demand-vs-server-mode
      - title: Learning Mode
        url: /prompt-alchemy/learning-mode
      - title: Scheduling
        url: /prompt-alchemy/scheduling
      - title: Mode FAQ
        url: /prompt-alchemy/mode-faq
  
  - title: "🔧 Development"
    children:
      - title: Testing
        url: /prompt-alchemy/testing
      - title: Multi-Arch Builds
        url: /prompt-alchemy/multi-arch-builds
      - title: Renovate Setup
        url: /prompt-alchemy/renovate-setup
      - title: Release Automation
        url: /prompt-alchemy/release-automation

# Jekyll Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins for enhanced functionality
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# SEO Plugin Settings
seo:
  type: WebSite
  name: Prompt Alchemy
  headline: AI Prompt Generation and Optimization Toolkit
  description: Transform raw ideas into high-quality prompts for AI systems through a three-phase refinement process
  url: https://jonwraymond.github.io/prompt-alchemy
  logo: https://jonwraymond.github.io/prompt-alchemy/assets/prompt_alchemy2.png

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gem"
  - "*.gemspec"
  - tools/
  - docs/
  - Rakefile
  - README.md
  - CHANGELOG.md
  - LICENSE
  - CNAME