# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: Prompt Alchemy
description: Advanced AI Prompt Generation and Optimization CLI Tool
baseurl: "/prompt-alchemy" # The repository name
url: "https://jonwraymond.github.io" # GitHub username from git URL

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Installation
    url: /installation
  - title: Usage Guide
    url: /usage
  - title: Architecture
    url: /architecture
  - title: Renovate Setup
    url: /renovate-setup
  - title: Release Automation
    url: /release-automation
  - title: Diagrams
    url: /diagrams
  - title: Database
    url: /database
  - title: MCP Integration
    url: /mcp-integration
  - title: MCP Tools
    url: /mcp-tools
  - title: CLI Reference
    url: /cli-reference
  - title: API Reference
    url: /api-reference

# Jekyll Settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
