# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: Prompt Alchemy
description: Transform raw ideas into golden prompts through the ancient art of linguistic alchemy
logo: /prompt-alchemy/assets/prompt_alchemy.png
logo2: /prompt-alchemy/assets/prompt_alchemy2.png
baseurl: "/prompt-alchemy" # The repository name
url: "https://jonwraymond.github.io" # GitHub username from git URL

# Branding
brand:
  primary_color: "#C9A96E"  # Alchemical gold
  secondary_color: "#8B4513"  # Ancient brown
  accent_color: "#DAA520"  # Goldenrod
  text_color: "#2C1810"  # Dark brown
  background_color: "#FFF8DC"  # Cornsilk

# Navigation
navigation:
  - title: Home
    url: /prompt-alchemy/
  - title: Getting Started
    url: /prompt-alchemy/getting-started
  - title: Installation
    url: /prompt-alchemy/installation
  - title: Usage Guide
    url: /prompt-alchemy/usage
  - title: Deployment
    url: /prompt-alchemy/deployment-guide
  - title: "On-Demand vs. Server Mode"
    url: /prompt-alchemy/on-demand-vs-server-mode
  - title: Learning Mode
    url: /prompt-alchemy/learning-mode
  - title: Scheduling
    url: /prompt-alchemy/scheduling
  - title: Testing
    url: /prompt-alchemy/testing
  - title: CLI Reference
    url: /prompt-alchemy/cli-reference
  - title: MCP API Reference
    url: /prompt-alchemy/mcp-api-reference
  - title: HTTP API Reference
    url: /prompt-alchemy/http-api-reference
  - title: Client Interaction Modes
    url: /prompt-alchemy/client-interaction-modes
  - title: Architecture
    url: /prompt-alchemy/architecture
  - title: Vector Embeddings
    url: /prompt-alchemy/vector-embeddings
  - title: Database
    url: /prompt-alchemy/database
  - title: Diagrams
    url: /prompt-alchemy/diagrams
  - title: Renovate Setup
    url: /prompt-alchemy/renovate-setup
  - title: Release Automation
    url: /prompt-alchemy/release-automation
  - title: Multi-Arch Builds
    url: /prompt-alchemy/multi-arch-builds

# Jekyll Settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
