# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: Prompt Alchemy
description: Transform raw ideas into golden prompts through the ancient art of linguistic alchemy
logo: /assets/prompt_alchemy.png
logo2: /assets/prompt_alchemy2.png
baseurl: "/prompt-alchemy" # The repository name
url: "https://jonwraymond.github.io" # GitHub username from git URL

# Branding
brand:
  primary_color: "#C9A96E"  # Alchemical gold
  secondary_color: "#8B4513"  # Ancient brown
  accent_color: "#DAA520"  # Goldenrod
  text_color: "#2C1810"  # Dark brown
  background_color: "#FFF8DC"  # Cornsilk

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Installation
    url: /installation
  - title: Usage Guide
    url: /usage
  - title: Deployment
    url: /deployment-guide
  - title: "On-Demand vs. Server Mode"
    url: /on-demand-vs-server-mode
  - title: Learning Mode
    url: /learning-mode
  - title: Scheduling
    url: /scheduling
  - title: Testing
    url: /testing
  - title: CLI Reference
    url: /cli-reference
  - title: MCP API Reference
    url: /mcp-api-reference
  - title: HTTP API Reference
    url: /http-api-reference
  - title: Client Interaction Modes
    url: /client-interaction-modes
  - title: Architecture
    url: /architecture
  - title: Vector Embeddings
    url: /vector-embeddings
  - title: Database
    url: /database
  - title: Diagrams
    url: /diagrams
  - title: Renovate Setup
    url: /renovate-setup
  - title: Release Automation
    url: /release-automation
  - title: Multi-Arch Builds
    url: /multi-arch-builds

# Jekyll Settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
